apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      # Reference the image pull secret so Kubernetes can authenticate to the registry
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: my-web-app
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        image: adrwalgitopslhfv.azurecr.io/my-web-app:f4d6ffc2691ccebec6987e20ffac622aca8d3673
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
