apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      # Reference the image pull secret so Kubernetes can authenticate to the registry
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: my-web-app
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        image: adrwalgitopsqgku.azurecr.io/my-web-app:a91794b56e6b6c96d8b96ef9637ad10227a7c9da
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
